-- insert currencies
-- depends: 20230825_12_Kb9XY-add-column-score-to-table-cards
INSERT INTO currencies(name, short_name)
VALUES ('Ruble', 'RUB'),
       ('Australian dollar', 'AUD'),
       ('Azerbaijani manat', 'AZN'),
       ('British pound sterling', 'GBP'),
       ('Armenian dram', 'AMD'),
       ('Belarusian ruble', 'BYN'),
       ('Bulgarian Lev', 'BGN'),
       ('Brazilian Real', 'BRL'),
       ('Hungarian forint', 'HUF'),
       ('Vietnamese dong', 'VND'),
       ('Hong Kong dollar', 'HKD'),
       ('Georgian lari', 'GEL'),
       ('Danish krone', 'DKK'),
       ('Dirham ОАЭ', 'AED'),
       ('U.S. dollar', 'USD'),
       ('Euro', 'EUR'),
       ('Egyptian pound', 'EGP'),
       ('Indian rupee', 'INR'),
       ('Indonesian rupiah', 'IDR'),
       ('Kazakhstani tenge', 'KZT'),
       ('Canadian dollar', 'CAD'),
       ('Qatari rial', 'QAR'),
       ('Kyrgyzstan Som', 'KGS'),
       ('Chinese Yuan', 'CNY'),
       ('Moldovan leu', 'MDL'),
       ('New Zealand dollar', 'NZD'),
       ('Norwegian krone', 'NOK'),
       ('Polish zloty', 'PLN'),
       ('Romanian leu', 'RON'),
       ('SDR (Special Drawing Rights)', 'XDR'),
       ('Singapore dollar', 'SGD'),
       ('Tajik somoni', 'TJS'),
       ('Thai baht', 'THB'),
       ('Turkish lira', 'TRY'),
       ('New Turkmen manat', 'TMT'),
       ('Uzbek sum', 'UZS'),
       ('Ukrainian hryvnia', 'UAH'),
       ('CZK', 'CZK'),
       ('Swedish kroner', 'SEK'),
       ('Swiss Franc', 'CHF'),
       ('Serbian dinar', 'RSD'),
       ('South African Rand', 'ZAR'),
       ('Won of the Republic of Korea', 'KRW'),
       ('Japanese yen', 'JPY')
;
