-- alter table name
-- depends: 20230824_01_tNaNK-initial-tables
ALTER TABLE USERS RENAME TO users;
ALTER TABLE WALLETS RENAME TO wallets;
ALTER TABLE HISTORYOPERATIONS RENAME TO history_operations;
ALTER TABLE BANKS RENAME TO banks;
ALTER TABLE TYPEOPERATIONENUM RENAME TO type_operation;

