USER_ALREADY_EXISTS = "Уже есть пользователь с данным адресом электронной почты"
PASSWORD_INCORRECT = "Введен неверный пароль"
USER_NOT_FOUND = "Пользователь с таким логином не существует"
BANK_NOT_FOUND = "Банк не найден"
WALLET_NOT_FOUND = "Кошелек не найден"
CARD_ALREADY_EXISTS = "Карта уже существует"
CARD_NOT_FOUND = "Карты не существует"
NOT_ENOUGH_MONEY = "Недостаточно средств"
